# Generated by Django 5.2 on 2025-05-24 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSalesDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '📊 Total Sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown', models.TextField()),
            ],
        ),
    ]
